### ISSUE TITLE
Can you give a link to get faster_rcnn_tf.model

### ISSUE THREAD

**Issue by philokey** [smallcorgi/Faster-RCNN_TF#1]
Hello!
I try to run demo.py, but I failed because I do not have faster_rcnn_tf.model. Can you give a link to get faster_rcnn_tf.model or the pre-trained VGG16 model. 
Thank you very much.

**Comment by smallcorgi** [comment]
Hello @philokey 
I have already uploaded the model. You can get model in Readme!

**Comment by philokey** [comment]
Thank you very much!

**Comment by kaishijeng** [comment]
Can you upload network definition, demo_net  (VGGnet_test) so that demo.py can be run?

Thanks

**Comment by smallcorgi** [comment]
Hi @kaishijeng,
I updated the demo.py. You can download the new demo.py and try it again.

**Comment by kaishijeng** [comment]
demo.py works OK now

Thanks,

**Comment by shuye-cheung** [comment]
Hi, @smallcorgi @kaishijeng 
./tools/demo.py works. However, I find the results (bounding boxes and corresponding scores) is not consistent when I run it twice or more. Do you encounter this problem? or any idea to fix it?

Thanks

**Comment by smallcorgi** [comment]
Hi @shuye-cheung ,
I found the problems in drop out layer.
If i don't use drop out in fc6 & fc7, the result will be the same.
You can try to comment out the drop out layer in /lib/networks/VGGnet_test.py.

Thanks,

**Comment by jiangjingyao** [comment]
Hi @smallcorgi @shuye-cheung @kaishijeng ,I have already  downloaded  VGG_imagenet.npy and put it in ./models/ ,but I failed to run demo.py. my command is "./tools/demo.py --model ./models/VGG_imagenet.npy".Can you give me  some suggestions ?

**Comment by shuye-cheung** [comment]
Hi, @smallcorgi ,
The problem is solved by commenting out the drop out layer. 

Thanks for your prompt advise~

**Comment by shuye-cheung** [comment]
Hi, @jiangjingyao I think you misunderstand the usage of VGG_imagenet.npy. VGG_imagenet.npy is a pre-trained model for training a new model. 

If you want to run ./tools/demo.py, you should try 
./tools/demo.py --model /path/to/VGGnet_fast_rcnn_iter_70000.ckpt

(VGGnet_fast_rcnn_iter_70000.ckpt is provide in readme)

**Comment by jiangjingyao** [comment]
Thanks for your help @shuye-cheung ,I still can't run it .There is an erro in line 24," ./tools/demo.py: line 24:  An unexpected syntax errors near`(' ".Do you encounter this problem? And how do you solve it?

Thanks

**Comment by yfor1008** [comment]
@jiangjingyao  "--model /path/to/VGGnet_fast_rcnn_iter_70000.ckpt" need a space between "--model" and the "/path/to/VGGnet_fast_rcnn_iter_70000.ckpt"
